import { createSlice } from '@reduxjs/toolkit';

const initialState = {
  books: [
    {
        id: 1,
        title: "To Kill a Mockingbird",
        author: "Harper Lee",
        publishedDate: "1960-07-11",
        isbn: "9780060935467",
        pages: 336,
        coverImage: "https://m.media-amazon.com/images/I/91HHqVTAJQL.jpg",
        description: "A timeless novel that delves into themes of racial injustice, moral growth, and compassion, set in the American South during the 1930s.",
        price: 10.99,
        genre: "Fiction",
        rating: 1,
      },
      

    {
      id: 2,
      title: "1984",
      author: "George Orwell",
      publishedDate: "1949-06-08",
      isbn: "9780451524935",
      pages: 328,
      coverImage: "https://m.media-amazon.com/images/I/81t2CVWEsUL.jpg",
      description: "A dystopian novel set in a totalitarian society ruled by Big Brother.",
      price: 8.99,
      genre: "Science Fiction",
      rating: 4.6,
    },
    {
      id: 3,
      title: "Pride and Prejudice",
      author: "Jane Austen",
      publishedDate: "1813-01-28",
      isbn: "9780141040349",
      pages: 279,
      coverImage: "https://m.media-amazon.com/images/I/91HHxxtA1wL.jpg",
      description: "A romantic novel that explores themes of class, marriage, and morality in 19th century England.",
      price: 6.99,
      genre: "Romance",
      rating: 3,
    },
    {
      id: 4,
      title: "The Great Gatsby",
      author: "F. Scott Fitzgerald",
      publishedDate: "1925-04-10",
      isbn: "9780743273565",
      pages: 180,
      coverImage: "https://m.media-amazon.com/images/I/81Q6WkLhX4L.jpg",
      description: "A novel about the decline of the American Dream in the 1920s.",
      price: 9.99,
      genre: "Classic",
      rating: 4,
    },
    {
      id: 5,
      title: "Moby Dick",
      author: "Herman Melville",
      publishedDate: "1851-11-14",
      isbn: "9780142437247",
      pages: 720,
      coverImage: "https://m.media-amazon.com/images/I/81gepf1eMqL.jpg",
      description: "An epic tale of a man's obsession with hunting a giant white whale.",
      price: 11.50,
      genre: "Adventure",
      rating: 4.3,
    },
    {
      id: 6,
      title: "The Catcher in the Rye",
      author: "J.D. Salinger",
      publishedDate: "1951-07-16",
      isbn: "9780316769488",
      pages: 277,
      coverImage: "https://m.media-amazon.com/images/I/81OthjkJBuL.jpg",
      description: "A novel about teenage rebellion and alienation.",
      price: 7.99,
      genre: "Fiction",
      rating: 2,
    },
    {
      id: 7,
      title: "Brave New World",
      author: "Aldous Huxley",
      publishedDate: "1932-08-30",
      isbn: "9780060850524",
      pages: 268,
      coverImage: "https://m.media-amazon.com/images/I/91D4YvdC0dL.jpg",
      description: "A dystopian novel that explores the dangers of technology and totalitarianism.",
      price: 12.99,
      genre: "Science Fiction",
      rating: 5,
    },
    {
      id: 8,
      title: "War and Peace",
      author: "Leo Tolstoy",
      publishedDate: "1869-01-01",
      isbn: "9780143039990",
      pages: 1296,
      coverImage: "https://m.media-amazon.com/images/I/81A-mvlo+QL.jpg",
      description: "An epic novel that chronicles the history of Russia during the Napoleonic era.",
      price: 15.99,
      genre: "Historical Fiction",
      rating: 4.7,
    },
    {
      id: 9,
      title: "Crime and Punishment",
      author: "Fyodor Dostoevsky",
      publishedDate: "1866-01-01",
      isbn: "9780486415871",
      pages: 430,
      coverImage: "https://m.media-amazon.com/images/I/71xBLRBYOiL.jpg",
      description: "A psychological novel that explores themes of guilt, redemption, and morality.",
      price: 9.50,
      genre: "Classic",
      rating: 3.6,
    },
    {
      id: 10,
      title: "The Hobbit",
      author: "J.R.R. Tolkien",
      publishedDate: "1937-09-21",
      isbn: "9780345339683",
      pages: 310,
      coverImage: "https://m.media-amazon.com/images/I/81t2CVWEsUL.jpg",
      description: "A fantasy novel about the adventures of a hobbit named Bilbo Baggins.",
      price: 13.99,
      genre: "Fantasy",
      rating: 1.8,
    },
  {
      id: 11,
      title: "The Road",
      author: "Cormac McCarthy",
      publishedDate: "2006-09-26",
      isbn: "9780307387899",
      pages: 287,
      coverImage: "https://m.media-amazon.com/images/I/51M7XGLQTBL._AC_UF1000,1000_QL80_.jpg",
      description: "A post-apocalyptic tale of a father and son's journey through a barren wasteland.",
      price: 10.50,
      genre: "Dystopian Fiction",
      rating: 3.4,
  },
  {
      id: 12,
      title: "The Kite Runner",
      author: "Khaled Hosseini",
      publishedDate: "2003-05-29",
      isbn: "9781594631931",
      pages: 371,
      coverImage: "https://m.media-amazon.com/images/I/81IzbD2IiIL._AC_UF1000,1000_QL80_.jpg",
      description: "A story about friendship, betrayal, and redemption in Afghanistan.",
      price: 8.99,
      genre: "Historical Fiction",
      rating: 4.7,
  },
  {
      id: 13,
      title: "The Book Thief",
      author: "Markus Zusak",
      publishedDate: "2005-03-14",
      isbn: "9780375842207",
      pages: 552,
      coverImage: "https://m.media-amazon.com/images/I/914cHl9v7oL._AC_UF1000,1000_QL80_.jpg",
      description: "The story of a young girl living in Nazi Germany who discovers the power of books.",
      price: 11.99,
      genre: "Historical Fiction",
      rating: 4.8,
  },
  {
      id: 14,
      title: "Life of Pi",
      author: "Yann Martel",
      publishedDate: "2001-09-11",
      isbn: "9780156027328",
      pages: 326,
      coverImage: "https://images-na.ssl-images-amazon.com/images/I/81vpsIs58WL.jpg",
      description: "A young boy survives a shipwreck and shares a lifeboat with a Bengal tiger.",
      price: 9.99,
      genre: "Adventure",
      rating: 4.6,
  },
  {
      id: 15,
      title: "The Handmaid's Tale",
      author: "Margaret Atwood",
      publishedDate: "1985-09-01",
      isbn: "9780385490818",
      pages: 311,
      coverImage: "https://m.media-amazon.com/images/I/61su39k8NUL._AC_UF1000,1000_QL80_.jpg",
      description: "A dystopian novel about a theocratic society in which women have lost all rights.",
      price: 10.99,
      genre: "Dystopian Fiction",
      rating: 4.5,
  },
  {
      id: 16,
      title: "The Shining",
      author: "Stephen King",
      publishedDate: "1977-01-28",
      isbn: "9780307743657",
      pages: 447,
      coverImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTG7dmU8popYbvB7Gds7_UwSP0CqsVAIIq00g&s",
      description: "A horror novel about a family staying in an isolated hotel that has a terrifying history.",
      price: 12.50,
      genre: "Horror",
      rating: 4.4,
  },
  {
      id: 17,
      title: "Fahrenheit 451",
      author: "Ray Bradbury",
      publishedDate: "1953-10-19",
      isbn: "9781451673319",
      pages: 158,
      coverImage: "https://m.media-amazon.com/images/I/61l8LHt4MeL._AC_UF1000,1000_QL80_.jpg",
      description: "A dystopian novel about a future where books are banned and 'firemen' burn any that are found.",
      price: 8.50,
      genre: "Science Fiction",
      rating: 4.3,
  },
  {
      id: 18,
      title: "The Fault in Our Stars",
      author: "John Green",
      publishedDate: "2012-01-10",
      isbn: "9780525478812",
      pages: 313,
      coverImage: "https://m.media-amazon.com/images/I/61fbVx3W5cL._AC_UF1000,1000_QL80_.jpg",
      description: "A touching story about two teenagers who fall in love while battling cancer.",
      price: 9.99,
      genre: "Young Adult",
      rating: 4.7,
  },
  {
      id: 19,
      title: "The Alchemist",
      author: "Paulo Coelho",
      publishedDate: "1988-01-01",
      isbn: "9780062315007",
      pages: 208,
      coverImage: "https://m.media-amazon.com/images/I/61HAE8zahLL._AC_UF1000,1000_QL80_.jpg",
      description: "A philosophical book that tells the story of a shepherd's journey to realize his dreams.",
      price: 10.99,
      genre: "Philosophical Fiction",
      rating: 4.6,
  },
  {
      id: 20,
      title: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
      author: "C.S. Lewis",
      publishedDate: "1950-10-16",
      isbn: "9780064404990",
      pages: 208,
      coverImage: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJhRlMBytU5j1ATA_zud4IUy5y_-xRnTwrzg&s",
      description: "A fantasy novel about four children who discover a magical land through a wardrobe.",
      price: 7.99,
      genre: "Fantasy",
      rating: 4.8,
  },

  ],
  filteredBooks: [],
};

const bookSlice = createSlice({
  name: 'book',
  initialState,
  reducers: {
    addBook: (state, action) => {
      state.books.push(action.payload);
    },
    filterBooksByCategory: (state, action) => {
      const category = action;
      state.filteredBooks = state.books.filter((book) => book.genre === category);
    },
  },
});

export const { addBook} = bookSlice.actions;
export default bookSlice.reducer;